from Views.buy import Purchases
from Views.transactions import *
from Views.login import Login
from Views.clients import Clients
from Views.suppliers import Suppliers
from Views.warehouses import Warehouses
from Views.products import Products
from Views.sales import Sales
from Views.users import Users
from Views.stock import Stock
