from Views.buy import *
from Views.transactions import *
from Views.login import Login
from Views.clients import Clients
from Views.suppliers import *
from Views.warehouses import *
from Views.products import Products
from Views.sales import *
from Views.users import Users
from Views.stock import *
