from Views.buy import *
from Views.history import *
from Views.login import *
from Views.newClient import *
from Views.newSupplier import *
from Views.newWhs import *
from Views.newProduct import *
from Views.sell import *
from Views.users import *
from Views.stock import *
