from Views.buy import *
from Views.transactions import *
from Views.login import *
from Views.clients import *
from Views.suppliers import *
from Views.warehouses import *
from Views.products import *
from Views.sales import *
from Views.users import *
from Views.stock import *
